api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),

    path('categories/', views.CategoryAutocomplete.as_view(), name="api-categories"),
    path('names/', views.NameAutocomplete.as_view(), name="api-names"),
    path('brands/', views.BrandAutocomplete.as_view(), name="api-brands"),
]

busman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    path('', home_views.home, name='home-home'),

    path('accounts/', include('users.urls')),   
    path('org/', include('organization.urls')),
    path('products/', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('purchase/', include('purchase.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sales/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.SalesInvoiceListView.as_view(), name='sales-list'),
    path('create/', views.SalesInvoiceCreateView.as_view(), name='sales-create'),
    path('<int:pk>/edit/', views.SalesInvoiceUpdateView.as_view(), name='sales-edit'),
    path('<int:pk>/view/', views.SalesInvoiceDetailView.as_view(), name='sales-view'),
    path('<int:pk>/print/', views.SalesInvoicePrintView.as_view(), name='sales-print'),
    path('<int:pk>/delete/', views.SalesInvoiceDeleteView.as_view(), name='sales-delete'),
    path('<int:pk>/entry/add/',
         views.SalesInvoiceEntryCreateView.as_view(), name='sales-entry-add'),
    path('entry/<int:pk>/delete/',
         views.SalesInvoiceEntryDeleteView.as_view(), name='sales-entry-delete'),

]

invoicing/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
import operator
from decimal import Decimal
from organization.models import Organization
from products.models import Product

# Create your models here.
"""Abstract models for invoicing(Purchase and Sales)"""


class Invoice(models.Model):

    name = models.CharField(max_length=255)  # Name of the vendor or customer
    date = models.DateField()
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name='%(class)s')

    class finalized(models.IntegerChoices):
        PENDING = 0
        FINALIZED = 1

    finalized = models.BooleanField(
        max_length=20, choices=finalized.choices, default=0)

    class Meta:
        abstract = True
        ordering = ["-id"]

    PURCHASE = operator.add
    SALE = operator.sub

    def finalize(self, action):
        if self.finalized == 0:
            for entry in self.entries.all():
                #Skip if the product has been deleted
                if entry.product:
                    entry.product.stock += action(0, entry.quantity)
                    entry.product.save()
                self.finalized = 1
                self.save()
            return True
        else:
            return False

    @property
    def gross_total(self):

        total = Decimal(0)
        for entry in self.entries.all():
            total += entry.total_price
        return total


class InvoiceEntry(models.Model):

    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, related_name='%(class)s')
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        abstract = True

    @property
    def total_price(self):
        return self.price * self.quantity

products/models.py
from django.db import models
from decimal import Decimal
import operator
from organization.models import Organization

# Create your models here.
class Product(models.Model):
    brand = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255)
    sale_price = models.DecimalField(decimal_places=2, max_digits=12)
    minimum_price = models.DecimalField(decimal_places=2, max_digits=12)
    stock = models.DecimalField(decimal_places=2, max_digits=12)
    unit = models.CharField(max_length=50, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='products')
    category = models.CharField(max_length=255, blank=True)

    class Meta:
        order_with_respect_to = 'organization'

    def __str__(self):
        return f"{self.brand} / {self.name} / Rs. {self.minimum_price}-{self.sale_price} / {self.stock} Remaining"

sales/models.py
from django.db import models
from django.urls import reverse
from invoicing.models import Invoice, InvoiceEntry

# Create your models here.
SALE = Invoice.SALE
class SalesInvoice(Invoice):

    discount = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, default=0)

    @property
    def net_total(self):
        return self.gross_total*(1-self.discount/100)
    
    def get_absolute_url(self):
        return reverse('sales-view', args=[self.pk])

    
class SalesInvoiceEntry(InvoiceEntry):

    invoice = models.ForeignKey(
        SalesInvoice, on_delete=models.CASCADE, related_name='entries')

    class Meta:
        verbose_name_plural = 'Sales Invoice Entries'

sales/forms.py
from django import forms
from .models import SalesInvoice, SalesInvoiceEntry
from invoicing.forms import InvoiceForm

class SalesInvoiceForm(InvoiceForm):
    class Meta(InvoiceForm.Meta):
        model = SalesInvoice
        labels = {
            'discount': 'Discount %'
        }


class SalesInvoiceEntryForm(forms.ModelForm):

    discount = forms.DecimalField(max_digits=12, decimal_places=2, initial=0)

    def save(self, *args, **kwargs):
        self.instance.price = self.instance.product.sale_price-self.cleaned_data["discount"]
        return super().save(*args, **kwargs)

    def clean(self):
        
        cleaned_data = super().clean()

        discount = cleaned_data.get('discount')
        sale_price = cleaned_data.get('product').sale_price
        minimum_price = cleaned_data.get('product').minimum_price

        if minimum_price > sale_price-discount:
            self.add_error('discount', 'Discount too high!')

    class Meta:
        model = SalesInvoiceEntry
        exclude = ['invoice', 'price']

sales/views.py
from django.urls import reverse_lazy
from .models import SalesInvoice, SalesInvoiceEntry, SALE
from .filters import SalesInvoiceFilter
from .forms import SalesInvoiceForm, SalesInvoiceEntryForm

from invoicing.views import (
    InvoiceListView,
    InvoiceCreateView, 
    InvoiceDetailView, 
    InvoiceUpdateView, 
    InvoiceDeleteView,
    InvoiceEntryCreateView,
    InvoiceEntryDeleteView)

# Create your views here.
class SalesInvoiceListView(InvoiceListView):
    model = SalesInvoice
    filterset_class = SalesInvoiceFilter
    template_name = "sales/salesinvoice_list.html"


class SalesInvoiceCreateView(InvoiceCreateView):
    model = SalesInvoice
    form_class = SalesInvoiceForm

class SalesInvoiceDetailView(InvoiceDetailView):
    model = SalesInvoice
    finalize_action = SALE
    invoice_finalize_redirect_name = 'sales-view'

class SalesInvoiceUpdateView(InvoiceUpdateView):
    model = SalesInvoice
    form_class = SalesInvoiceForm
   
class SalesInvoiceDeleteView(InvoiceDeleteView):
    model = SalesInvoice
    success_url = reverse_lazy('sales-list')

class SalesInvoiceEntryCreateView(InvoiceEntryCreateView):
    model = SalesInvoiceEntry
    parent_model = SalesInvoice
    action = SalesInvoice.SALE
    form_class = SalesInvoiceEntryForm
        

class SalesInvoiceEntryDeleteView(InvoiceEntryDeleteView):
    model = SalesInvoiceEntry

class SalesInvoicePrintView(InvoiceDetailView):
    model = SalesInvoice
    template_name = 'sales/salesinvoice_print.html'

sales/templates/sales/add_entries.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Add Entries to invoice</h5>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary" value="Add">
                    <a href="{% url 'sales-view' pk %}" class="btn btn-secondary">Back</a>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Added Entries</h5>
                <div class="table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Brand</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entry in added_entries %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ entry.product.brand }}</td>
                                <td>{{ entry.product.name }}</td>
                                <td>{{ entry.price }}</td>
                                <td>{{ entry.quantity }}</td>
                                <td>{{ entry.total_price|floatformat:2 }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extras %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"
        integrity="sha512-hgoywpb1bcTi1B5kKwogCTG4cvTzDmFCJZWjit4ZimDIgXu7Dwsreq8GOQjKVUxFwxCWkLcJN5EN0W0aOngs4g=="
        crossorigin="anonymous"></script>   
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css"
        integrity="sha512-nATinx3+kN7dKuXEB0XLIpTd7j8QahdyJjE24jTJf4HASidUCFFN/TkSVn3CifGmWwfC2mO/VmFQ6hRn2IcAwg=="
        crossorigin="anonymous" />
    <script>
        $('#id_product').selectize({
                sortField: 'text'
            });
    </script>
{% endblock %}

sales/templates/sales/invoice_confirm_delete.html
{% extends 'home/base.html' %}
{% block content %}
<div class="gray-bg pb-3 pt-3">
    <div class="container">
        <div class="card border-danger text-center">
            <div class="card-header">
                Are you sure you want to delete this Invoice?
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th>Customer</th>
                                <th>Date</th>
                                <th>Gross Value</th>
                                <th>Discount %</th>
                                <th>Net Value</th>
                            </tr>
                        </thead>
                        <tr>
                            <td>{{ object.customer_name }}</td>
                            <td>{{ object.date }}</td>
                            <td>{{ object.gross_total|floatformat:2 }}</td>
                            <td>{{ object.discount }}</td>
                            <td>{{ object.net_total|floatformat:2 }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="card-footer border-danger">
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="submit" name="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sales/templates/sales/invoice_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">

    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <small class="text-muted float-right"><a href="{{request.url}}">Reset</a></small>
                    {% if object %}
                    Edit Invoice
                    {% else %}
                    Create Invoice
                    {% endif %}
                </h5>

                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">{{ form.customer_name|as_crispy_field}}</div>
                        <div class="col-md-4">{{ form.date|as_crispy_field}}</div>
                        <div class="col-md-2">{{ form.discount|as_crispy_field}}</div>
                    </div>
                    {% if object%}
                    <input type="submit" value="Update" class="btn btn-primary"><a href="javascript:history.back()" class="btn btn-secondary ml-2">Back</a>
                    {% else %}
                    <input type="submit" value="Add" class="btn btn-primary"><a href="javascript:history.back()" class="btn btn-secondary ml-2">Back</a>
                    {% endif%}
                </form>
            </div>
        </div>

    </div>


</div>
{% endblock %}
{% block extras%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
    crossorigin="anonymous"></script>
<script>
    $(function () {
        $("#id_category").autocomplete({
            source: '{% url "api-categories" %}',
            minLength: 1
        })
    })
</script>
{% endblock %}

sales/templates/sales/invoice_list.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h5>Invoices <a href="{% url 'sales-create' %}" class="btn btn-outline-primary">Create</a></h5>
                </div>
                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link text-left" type="button" data-toggle="collapse"
                                    data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                    Filter List
                                </button>
                                <small class="text-muted float-right"><a
                                        href="{% url 'sales-list' %}">Clear</a></small>
                            </h5>
                        </div>

                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <form action="" method="GET">
                                    {{ filter.form|crispy }}
                                    <input type="submit" value="Search" class="btn btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive mt-3">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Customer Name</th>
                                <th>Value</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        {% for invoice in page_obj %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td><a href="{% url 'sales-view' invoice.pk %}">{{ invoice.customer_name }}</a></td>
                            <td>{{ invoice.gross_total|floatformat:2 }}</td>
                            <td>{{ invoice.get_finalized_display }}</td>
                            <td>{{ invoice.date }}</td>
                            <td><a href="{% url 'sales-delete' invoice.pk %}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td style="text-align: center;" colspan="6">No Invoices found!</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="pagination d-flex flex-column">
                    {% if is_paginated %}

                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                            <li class="page-item"><a class="page-link"
                                    href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }} of
                                    {{ page_obj.paginator.num_pages }}</a></li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link"
                                    href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            <li class="page-item"><a class="page-link"
                                    href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                            {% endif %}

                        </ul>
                    </nav>

                    {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extras %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
    crossorigin="anonymous"></script>
<script>
    $(function () {
        $("#id_category").autocomplete({
            source: '{% url "api-categories" %}',
            minLength: 1
        })
        $("#id_name").autocomplete({
            source: '{% url "api-names" %}',
            minLength: 1
        })
        $("#id_brand").autocomplete({
            source: '{% url "api-brands" %}',
            minLength: 1
        })
    })
</script>
{% endblock %}

sales/templates/sales/invoiceentry_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Add Entries to invoice</h5>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary" value="Add">
                    <a href="{% url 'sales-view' pk %}" class="btn btn-secondary">Back</a>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Added Entries</h5>
                <div class="table-responsive mt-3">

                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entry in added_entries %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ entry.product.name }}</td>
                                <td>{{ entry.price }}</td>
                                <td>{{ entry.quantity }}</td>
                                <td>{{ entry.total_price|floatformat:2 }}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td style="text-align: center;" colspan="6">No products found!</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extras %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"
    integrity="sha512-hgoywpb1bcTi1B5kKwogCTG4cvTzDmFCJZWjit4ZimDIgXu7Dwsreq8GOQjKVUxFwxCWkLcJN5EN0W0aOngs4g=="
    crossorigin="anonymous"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css"
    integrity="sha512-nATinx3+kN7dKuXEB0XLIpTd7j8QahdyJjE24jTJf4HASidUCFFN/TkSVn3CifGmWwfC2mO/VmFQ6hRn2IcAwg=="
    crossorigin="anonymous" />
<script>
    $('#id_product').selectize({
        sortField: 'text'
    });
</script>
{% endblock %}

sales/templates/sales/salesinvoice_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">

    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <small class="text-muted float-right"><a href="{{request.url}}">Reset</a></small>
                    {% if object %}
                    Edit Invoice
                    {% else %}
                    Create Invoice
                    {% endif %}
                </h5>

                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">{{ form.name|as_crispy_field}}</div>
                        <div class="col-md-4">{{ form.date|as_crispy_field}}</div>
                        <div class="col-md-2">{{ form.discount|as_crispy_field}}</div>
                    </div>
                    {% if object%}
                    <input type="submit" value="Update" class="btn btn-primary"><a href="javascript:history.back()" class="btn btn-secondary ml-2">Back</a>
                    {% else %}
                    <input type="submit" value="Add" class="btn btn-primary"><a href="javascript:history.back()" class="btn btn-secondary ml-2">Back</a>
                    {% endif%}
                </form>
            </div>
        </div>

    </div>


</div>
{% endblock %}
{% block extras%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
    crossorigin="anonymous"></script>
<script>
    $(function () {
        $("#id_category").autocomplete({
            source: '{% url "api-categories" %}',
            minLength: 1
        })
    })
</script>
{% endblock %}

sales/templates/sales/salesinvoice_list.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h5>Invoices <a href="{% url 'sales-create' %}" class="btn btn-outline-primary">Create</a></h5>
                </div>
                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link text-left" type="button" data-toggle="collapse"
                                    data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                    Filter List
                                </button>
                                <small class="text-muted float-right"><a
                                        href="{% url 'sales-list' %}">Clear</a></small>
                            </h5>
                        </div>

                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                            data-parent="#accordionExample">
                            <div class="card-body">
                                <form action="" method="GET">
                                    {{ filter.form|crispy }}
                                    <input type="submit" value="Search" class="btn btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive mt-3">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Customer Name</th>
                                <th>Value</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        {% for invoice in page_obj %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td><a href="{% url 'sales-view' invoice.pk %}">{{ invoice.name }}</a></td>
                            <td>{{ invoice.gross_total|floatformat:2 }}</td>
                            <td>{{ invoice.get_finalized_display }}</td>
                            <td>{{ invoice.date }}</td>
                            <td><a href="{% url 'sales-delete' invoice.pk %}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td style="text-align: center;" colspan="6">No Invoices found!</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                {% include 'organization/partials/pagination.html' %}

            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extras %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
    crossorigin="anonymous"></script>
{% endblock %}

sales/templates/sales/salesinvoiceentry_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="gray-bg pt-3 pb-3">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Add Entries to invoice</h5>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary" value="Add">
                    <a href="{% url 'sales-view' pk %}" class="btn btn-secondary">Back</a>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Added Entries</h5>
                <div class="table-responsive mt-3">

                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entry in added_entries %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ entry.product.name }}</td>
                                <td>{{ entry.price }}</td>
                                <td>{{ entry.quantity }}</td>
                                <td>{{ entry.total_price|floatformat:2 }}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td style="text-align: center;" colspan="6">No products found!</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extras %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"
    integrity="sha512-hgoywpb1bcTi1B5kKwogCTG4cvTzDmFCJZWjit4ZimDIgXu7Dwsreq8GOQjKVUxFwxCWkLcJN5EN0W0aOngs4g=="
    crossorigin="anonymous"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css"
    integrity="sha512-nATinx3+kN7dKuXEB0XLIpTd7j8QahdyJjE24jTJf4HASidUCFFN/TkSVn3CifGmWwfC2mO/VmFQ6hRn2IcAwg=="
    crossorigin="anonymous" />
<script>
    $('#id_product').selectize({
        sortField: 'text'
    });
</script>
{% endblock %}